### PR TITLE
fixes a bug with SVD result shaping

### LINKED ISSUE #6: SVD Image shaping
The following fails:

``` python
data = thunder.images.fromrandom((10, 100))
model = factorization.SVD().fit(data)
```

The error indicates that problem is in the code that tries to reshape the output to match the shape of the original `Images` object.

Further debugging confirms that this is the case. The code was written assuming that the result of a factorization is two matrices -- `X = AB`. Then, in the case where `X` is an `Images` object, the second result should be reshaped to match the shape of the images. However, with `SVD`, our factorization returns three terms -- `X = ABC`. So the correct general solution is reshaping the _last_ result, as opposed to the _second_ result.

### PR DESCRIPTION
**Pull request by jwittenbach**
Fixes #6.

### CODE REVIEW

**Comment by boazmohar** [comment]
@jwittenbach could you publish this to pypy, version 1.0 still has this bug.

**Comment by jwittenbach** [comment]
@boazmohar unfortunately, I can't -- @freeman-lab is I think the only one with access to that.

**Comment by boazmohar** [comment]
Should I open an issue?

**Comment by jwittenbach** [comment]
Let's see if we can get @freeman-lab here; if not, then we can open an issue.

**Comment by freeman-lab** [comment]
i'll publish! sorry for leaving this hanging

**Pull request merged**
